version: '2'
services:
    cinemeld-webapp:
        container_name: cinemeld-webapp
        build:
            dockerfile: Dockerfile.local
            context: $PWD/../../dev/cinemeld-webapp-dev
        volumes:
            - $PWD/../../dev/cinemeld-webapp-dev/source:/code/source
        ports:
            - "0.0.0.0:3000:3000"
    general-backend:
        container_name: general-backend
        build:
            dockerfile: Dockerfile.local
            context: $PWD/../../prod/general-backend
        volumes:
            - $PWD/../../prod/general-backend:/code/source
        ports:
            - 8000:8000
        