version: '2'
services:
    cinemeld-webapp:
        container_name: cinemeld-webapp
        build:
            dockerfile: Dockerfile.local
            context: $PWD/../../cinemeld-webapp
        volumes:
            - $PWD/../../cinemeld-webapp/source:/code/source
        ports:
            - 3000:3000
        